export const Icons = {
  //-------------Bottom Tab Icons // Dont use these anywhere else
  // bottomtab_icon_inactive_sales: require('../assets/icons/bottomtab_icon_inactive_sales.png'),
  bottomtab_icon_inactive_orders: require('../assets/icons/bottomtab_icon_inactive_orders.png'),
  bottomtab_icon_inactive_home: require('../assets/icons/bottomtab_icon_inactive_home.png'),
  bottomtab_icon_inactive_profile: require('../assets/icons/bottomtab_icon_inactive_profile.png'),
  bottomtab_icon_inactive_search: require('../assets/icons/heart.png'),
  // bottomtab_icon_active_sales: require('../assets/icons/bottomtab_icon_active_sales.png'),
  bottomtab_icon_active_orders: require('../assets/icons/bottomtab_icon_inactive_orders.png'),
  bottomtab_icon_active_home: require('../assets/icons/bottomtab_icon_inactive_home.png'),
  // bottomtab_icon_active_profile: require('../assets/icons/bottomtab_icon_active_profile.png'),
  bottomtab_icon_active_search: require('../assets/icons/heart.png'),
  //-------------Non Formatted Icon
  //-------------Formatted Icon
  search_textbox_icon: require('../assets/icons/search_textbox_icon.png'),
  //-------------Other Icons
  GobackHeader: require('../assets/icons/previous.png'),
  home: require('../assets/icons/home.png'),
  // selectedHome: require('../assets/icons/selectedHome.png'),
  search: require('../assets/icons/search.png'),
  // selectedSearch: require('../assets/icons/selectedSearch.png'),
  // sale: require('../assets/icons/sale.png'),
  // selectedsale: require('../assets/icons/selectedsale.png'),
  order: require('../assets/icons/order.png'),
  // selectedorder: require('../assets/icons/selectedorder.png'),
  // profile: require('../assets/icons/profile.png'),
  // selectedprofile: require('../assets/icons/selectedprofile.png'),
  // Edit: require('../assets/icons/Edit.png'),
  // Password: require('../assets/icons/Password.png'),
  // Privacy: require('../assets/icons/Privacy.png'),
  // Contact: require('../assets/icons/Contact.png'),
  // Payment: require('../assets/icons/Payment.png'),
  // location: require('../assets/icons/location.png'),
  // userProfile: require('../assets/icons/userProfile.png'),
  Cart: require('../assets/icons/Carts.png'),
  // shopping_cart: require('../assets/icons/shopping_cart.png'),
  // Filter: require('../assets/icons/Filter.png'),
  // SortFilter: require('../assets/icons/SortFilter.png'),
  Next: require('../assets/icons/Next.png'),
  Bin: require('../assets/icons/Bin.png'),
  // circleDp: require('../assets/icons/circleDp.png'),
  delete: require('../assets/icons/delete.png'),
  deleteBold: require('../assets/icons/deleteBold.png'),
  // editBold: require('../assets/icons/editBold.png'),
  // locationSolid: require('../assets/icons/locationSolid.png'),
  whiteBackIcon: require('../assets/icons/whiteBackIcon.png'),
  menu:require('../assets/icons/menu.png'),
  heartFill:require('../assets/icons/heartfill.png'),
  purchase:require('../assets/icons/purchase.png'),
  users:require('../assets/icons/users.png'),
  dot:require('../assets/icons/dot.jpg'),
};
